### ISSUE TITLE
Some Nautilus & Wayland warnings, maybe also QT?

### ISSUE THREAD

**Issue by DuncanLithgow** [EmixamPP/synology-drive#5]
I'm getting this warning, I thought it was best to let you know.

`$ Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
debug.message: Cannot find path by key "user_cloud_station_app_path"
debug.message: Cannot find path by key "user_cloud_station_data_path"
debug.message: Cannot find path by key "user_cloud_station_working_dir_path"
debug.message: Cannot find path by key "user_cloud_station_drive_ui_path"
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QObject::connect: Incompatible sender/receiver arguments
        GlobalConnecter::sigTriggerThreeWayMerge(quint64) --> DaemonManager::slotIssueThreeWayMergeEvent(uint64_t)

** (org.gnome.Nautilus:13448): WARNING **: 16:53:12.605: Unable to initialize tag manager: Could not override fts5 tokenizer: SQL logic error
** Message: 16:53:12.606: Connecting to org.freedesktop.Tracker3.Miner.Files

** (org.gnome.Nautilus:13466): WARNING **: 16:53:17.117: Unable to initialize tag manager: Could not override fts5 tokenizer: SQL logic error
** Message: 16:53:17.117: Connecting to org.freedesktop.Tracker3.Miner.Files
gtk-update-icon-cache: Cache file created successfully.

** (org.gnome.Nautilus:13466): WARNING **: 16:53:18.064: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5645bb3540b0

** (org.gnome.Nautilus:13466): WARNING **: 16:53:18.064: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5645bb2db880

** (org.gnome.Nautilus:13466): WARNING **: 16:53:18.064: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5645bb30c350

** (org.gnome.Nautilus:13466): WARNING **: 16:53:18.064: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5645bb354630

** (org.gnome.Nautilus:13466): WARNING **: 16:53:18.064: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5645bb2e01c0

** (org.gnome.Nautilus:13466): WARNING **: 16:53:18.064: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5645bb354820

** (org.gnome.Nautilus:13466): WARNING **: 16:53:18.064: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5645bb3549e0

** (org.gnome.Nautilus:13466): WARNING **: 16:53:18.064: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5645bb354e90

** (org.gnome.Nautilus:13466): WARNING **: 16:53:18.064: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5645bb355020
$ 
`

... I'll keep testing that everything still works.

**Comment by ppiutti** [comment]
I have the same experience on Fedora 38 (Files/Nautilus 44.1). Everything seems to be working fine but I have a similar series of warnings:


$ Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
debug.message: Cannot find path by key "user_cloud_station_app_path"
debug.message: Cannot find path by key "user_cloud_station_data_path"
debug.message: Cannot find path by key "user_cloud_station_working_dir_path"
debug.message: Cannot find path by key "user_cloud_station_drive_ui_path"
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QObject::connect: Incompatible sender/receiver arguments
        GlobalConnecter::sigTriggerThreeWayMerge(quint64) --> DaemonManager::slotIssueThreeWayMergeEvent(uint64_t)

** (org.gnome.Nautilus:6399): WARNING **: 10:24:20.151: Unable to initialize tag manager: Could not override fts5 tokenizer: SQL logic error
** Message: 10:24:20.151: Connecting to org.freedesktop.Tracker3.Miner.Files

** (org.gnome.Nautilus:6411): WARNING **: 10:24:21.179: Unable to initialize tag manager: Could not override fts5 tokenizer: SQL logic error
** Message: 10:24:21.179: Connecting to org.freedesktop.Tracker3.Miner.Files
gtk-update-icon-cache: Cache file created successfully.

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:24:21.411: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:24:21.556: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

** (org.gnome.Nautilus:6411): WARNING **: 10:24:21.566: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652e9c54670

** (org.gnome.Nautilus:6411): WARNING **: 10:24:21.566: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652e9c97840

** (org.gnome.Nautilus:6411): WARNING **: 10:24:21.566: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652e9c98c90

** (org.gnome.Nautilus:6411): WARNING **: 10:24:21.566: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652e9c9a110

** (org.gnome.Nautilus:6411): WARNING **: 10:24:21.566: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652ea37ab30

** (org.gnome.Nautilus:6411): WARNING **: 10:24:21.566: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652ea16e0c0

** (org.gnome.Nautilus:6411): WARNING **: 10:24:21.566: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652e9cbeab0

** (org.gnome.Nautilus:6411): WARNING **: 10:24:21.566: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652e9cc1720

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:24:21.668: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

** (org.gnome.Nautilus:6411): WARNING **: 10:25:27.821: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652ead28ea0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:26:00.925: AdwGizmo 0x5652eb406090 (tabboxchild) reported min width -6, but sizes must be >= 0

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eac6d620

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadea990

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eac6d780

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652ead02680

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc48f0

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc4aa0

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652e98f5f30

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc5150

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc5350

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc55a0

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc57b0

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc5a40

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc5c50

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc5ea0

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc6150

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc63d0

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc6630

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc6880

** (org.gnome.Nautilus:6411): WARNING **: 10:26:00.951: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadc6ad0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:26:00.989: AdwGizmo 0x5652eb406090 (tabboxchild) reported min width -6, but sizes must be >= 0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:26:01.051: AdwGizmo 0x5652eb406090 (tabboxchild) reported min width -6, but sizes must be >= 0

** (org.gnome.Nautilus:6411): WARNING **: 10:27:54.817: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eadbe5e0
[ppiutti@helium-vgeeklabs-lan applications]$ 
(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:32:57.128: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

** (org.gnome.Nautilus:6411): WARNING **: 10:32:57.153: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eab239e0

** (org.gnome.Nautilus:6411): WARNING **: 10:32:57.154: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eab5af20

** (org.gnome.Nautilus:6411): WARNING **: 10:32:57.154: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652ead557e0

** (org.gnome.Nautilus:6411): WARNING **: 10:32:57.154: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652ea269320

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:32:57.262: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:32:58.496: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:32:58.617: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:33:02.868: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:33:02.978: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:33:03.933: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

** (org.gnome.Nautilus:6411): WARNING **: 10:33:03.943: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eace1ae0

** (org.gnome.Nautilus:6411): WARNING **: 10:33:03.943: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eaae15c0

** (org.gnome.Nautilus:6411): WARNING **: 10:33:03.943: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652e9b6e580

** (org.gnome.Nautilus:6411): WARNING **: 10:33:03.943: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eabf6390

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:33:04.056: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:33:04.723: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

** (org.gnome.Nautilus:6411): WARNING **: 10:33:04.738: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eacea8b0

** (org.gnome.Nautilus:6411): WARNING **: 10:33:04.738: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652ebce8af0

** (org.gnome.Nautilus:6411): WARNING **: 10:33:04.738: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eb675010

** (org.gnome.Nautilus:6411): WARNING **: 10:33:04.738: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x5652eb5b42e0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:33:04.852: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:33:05.331: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0

(org.gnome.Nautilus:6411): Gtk-WARNING **: 10:33:05.451: AdwGizmo 0x5652ea157a50 (tabboxchild) reported min width -6, but sizes must be >= 0


Pasting it here in case it is helpful. And thanks for putting this RPM together, it was much needed.

**Comment by EmixamPP** [comment]
Sorry, I don't think I can do anything about these warnings. They are probably related to the binary generated by Synology.

Anyway, this doesn't cause any real problems.

**Comment by smidm** [comment]
This problem actually causes nautilus crashes on Fedora 39, GNOME nautilus 45.2.1 when using search function. When is the extension installed, the Files app crashes during search.

How to reproduce:

1. start Files
2. start typing at least 4-5 letters 
3. Files crashes

nautilus is logging lot of errors in the extension:

** (org.gnome.Nautilus:25151): WARNING **: 18:15:07.564: Unexpected plugin response.  This probably indicates a bug in a Nautilus extension: handle=0x559881875d60

backtrace:

```
Thread 1 "nautilus" received signal SIGSEGV, Segmentation fault.
0x000055555562864a in info_provider_idle_callback (user_data=user_data@entry=0x5555586b04e0) at ../src/nautilus-directory-async.c:4284
4284        if (response->handle != directory->details->extension_info_in_progress
Missing separate debuginfos, use: dnf debuginfo-install gnome-terminal-nautilus-3.50.1-1.fc39.x86_64 gstreamer1-1.22.9-1.fc39.x86_64 gstreamer1-plugins-bad-free-libs-1.22.9-1.fc39.x86_64 libedit-3.1-48.20230828cvs.fc39.x86_64 libpciaccess-0.16-9.fc39.x86_64 libunwind-1.7.0-0.2.rc2.fc39.x86_64 llvm-libs-17.0.6-3.fc39.x86_64 lm_sensors-libs-3.6.0-14.fc39.x86_64 mesa-dri-drivers-23.3.6-1.fc39.x86_64 mesa-libEGL-23.3.6-1.fc39.x86_64 mesa-libGL-23.3.6-1.fc39.x86_64 mesa-libgbm-23.3.6-1.fc39.x86_64 mesa-libglapi-23.3.6-1.fc39.x86_64 ncurses-libs-6.4-7.20230520.fc39.1.x86_64 nettle-3.9.1-2.fc39.x86_64 openldap-2.6.6-1.fc39.x86_64 orc-0.4.33-3.fc39.x86_64
(gdb) bt
#0  0x000055555562864a in info_provider_idle_callback (user_data=user_data@entry=0x5555586b04e0) at ../src/nautilus-directory-async.c:4284
#1  0x00007ffff7e9a78d in g_idle_dispatch (source=0x555559447a30, callback=0x555555628630 <info_provider_idle_callback>, user_data=0x5555586b04e0) at ../glib/gmain.c:6282
#2  0x00007ffff7e9de5c in g_main_dispatch (context=0x555555702be0) at ../glib/gmain.c:3476
#3  g_main_context_dispatch_unlocked (context=0x555555702be0) at ../glib/gmain.c:4284
#4  0x00007ffff7ef8f18 in g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x555555702be0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:4349
#5  0x00007ffff7e9bad3 in g_main_context_iteration (context=context@entry=0x555555702be0, may_block=may_block@entry=1) at ../glib/gmain.c:4414
#6  0x00007ffff751292d in g_application_run (application=application@entry=0x5555556ed680, argc=argc@entry=1, argv=argv@entry=0x7fffffffd9f8) at ../gio/gapplication.c:2577
#7  0x000055555558e58e in main (argc=1, argv=0x7fffffffd9f8) at ../src/nautilus-main.c:81
```

workaround:

remove the extension from /usr/lib64/nautilus/extensions-4/ and restart nautilus

**Comment by EmixamPP** [comment]
Synology has just released a new version, and the build on Fedora Copr has just finished. Maybe the update will fix the problem, but I doubt it., they don't mention a fix for Linux in their patch note. We'll probably have to wait until Ubuntu suffers from this bug too.

**Comment by smidm** [comment]
The bug is still present in synology-drive-3.5.0-16084.fc39.x86_64.
